model:
  vocab_size: 5000
  d_model: 512
  n_heads: 8
  n_layers: 6
  d_ff: 2048
  max_seq_len: 512
  dropout: 0.1

training:
  batch_size: 16
  learning_rate: 0.0001
  num_epochs: 10
  device: "cuda"

data:
  shakespeare_url: "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"